export const TopSixProjectsList = [
    {
        title: "titre",
        description: "description",
        image:"/projects/blabla.png",
        tags: ["react", "php", "Symfony"],
        link: "#",
        github: "#",
    },
    {
        title: "titre",
        description: "description",
        image:"/projects/blabla.png",
        tags: ["react", "php", "Symfony"],
        link: "#",
        github: "#",
    },
    {
        title: "titre",
        description: "description",
        image:"/projects/blabla.png",
        tags: ["react", "php", "Symfony"],
        link: "#",
        github: "#",
    },
    {
        title: "titre",
        description: "description",
        image:"/projects/blabla.png",
        tags: ["react", "php", "Symfony"],
        link: "#",
        github: "#",
    },
    {
        title: "titre",
        description: "description",
        image:"/projects/blabla.png",
        tags: ["react", "php", "Symfony"],
        link: "#",
        github: "#",
    },
    {
        title: "titre",
        description: "description",
        image:"/projects/blabla.png",
        tags: ["react", "php", "Symfony"],
        link: "#",
        github: "#",
    },
];

